# Summary

The following code extracts the content of each table (which may be contained in 1 PDF file, or split across 2 PDF files) and put this into a master dataframe. The "Main Loop" calls the various functions that are defined.

# Import Packages

In [25]:
import tabula
import os
import pandas as pd
%config IPCompleter.greedy=True
pd.options.display.max_columns = 50
pd.options.display.max_rows = 50

# Define Function split_table_handler()

In [26]:
# this functions handles the case in whereby the table is split across 2 pages
# handles known split-points (i.e. tables may be split at differnt rows)

def split_table_handler(df1, df2, split_type):
    
    if split_type == 1:
        df1_column_drop = ['Unnamed: 0','Unnamed: 1','Unnamed: 2']
        df1_labels_drop = [0,1,2,3,4,5,6,7,9,14,22,24,25,26,28,33,34,43,45]
        df1_index_names = ['prem_acc_direct','prem_acc_rein_sg','prem_acc_rein_asean','prem_acc_rein_other',
                           'prem_acc_total_rein','prem_cede_rein_sg','prem_cede_rein_asean','prem_cede_rein_other',
                           'prem_cede_rein_total','prem_write_net','prem_liab_begin','prem_liab_end','prem_earned',
                           'claim_set_direct','claim_set_rein_sg','claim_set_rein_asean','claim_set_rein_other',
                           'claim_set_total_rein','claim_rcv_rein_sg','claim_rcv_rein_asean','claim_rcv_rein_other',
                           'claim_rcv_rein_total','claim_set_net','claim_liab_end','claim_liab_begin',
                           'claim_incur_net','exp_management','exp_comm_paid','exp_comm_earned','exp_comm_incur_net']
        df2_column_drop = [0,1]
        df2_labels_drop = [1,5]
        df2_index_names = ['exp_other','uw_gain','net_invest_income','operating_result']

    elif split_type == 2:
        df1_column_drop = ['Unnamed: 0','Unnamed: 1','Unnamed: 2']
        df1_labels_drop = [0,1,2,3,4,5,6,7,9,14,23,24,26,31,40,42]
        df1_index_names = ['prem_acc_direct','prem_acc_rein_sg','prem_acc_rein_asean','prem_acc_rein_other',
                           'prem_acc_total_rein','prem_cede_rein_sg','prem_cede_rein_asean','prem_cede_rein_other',
                           'prem_cede_rein_total','prem_write_net','prem_liab_begin','prem_liab_end','prem_earned',
                           'claim_set_direct','claim_set_rein_sg','claim_set_rein_asean','claim_set_rein_other',
                           'claim_set_total_rein','claim_rcv_rein_sg','claim_rcv_rein_asean','claim_rcv_rein_other',
                           'claim_rcv_rein_total','claim_set_net','claim_liab_end','claim_liab_begin',
                           'claim_incur_net','exp_management','exp_comm_paid','exp_comm_earned','exp_comm_incur_net']
        df2_column_drop = [0,1]
        df2_labels_drop = [1,5]
        df2_index_names = ['exp_other','uw_gain','net_invest_income','operating_result']
    
    elif split_type == 3:
        df1_column_drop = ['Unnamed: 0','Unnamed: 1','Unnamed: 2']
        df1_labels_drop = [0,1,2,3,4,5,6,7,9,14,23,24,26,31,32,41,43,48]
        df1_index_names = ['prem_acc_direct','prem_acc_rein_sg','prem_acc_rein_asean','prem_acc_rein_other',
                           'prem_acc_total_rein','prem_cede_rein_sg','prem_cede_rein_asean','prem_cede_rein_other',
                           'prem_cede_rein_total','prem_write_net','prem_liab_begin','prem_liab_end','prem_earned',
                           'claim_set_direct','claim_set_rein_sg','claim_set_rein_asean','claim_set_rein_other',
                           'claim_set_total_rein','claim_rcv_rein_sg','claim_rcv_rein_asean','claim_rcv_rein_other',
                           'claim_rcv_rein_total','claim_set_net','claim_liab_end','claim_liab_begin',
                           'claim_incur_net','exp_management','exp_comm_paid','exp_comm_earned','exp_comm_incur_net',
                           'exp_other','uw_gain']
        df2_column_drop = [0,1]
        df2_labels_drop = [2]
        df2_index_names = ['net_invest_income','operating_result']

    elif split_type == 4:
        df1_column_drop = ['Unnamed: 0','Unnamed: 1','Unnamed: 2']
        df1_labels_drop = [0,1,2,3,4,5,6,7,9,14,20,22,24,26,27,28,30,35,36,43,45,47,49]
        df1_index_names = ['prem_acc_direct','prem_acc_rein_sg','prem_acc_rein_asean','prem_acc_rein_other',
                           'prem_acc_total_rein','prem_cede_rein_sg','prem_cede_rein_asean','prem_cede_rein_other',
                           'prem_cede_rein_total','prem_write_net','prem_liab_begin','prem_liab_end','prem_earned',
                           'claim_set_direct','claim_set_rein_sg','claim_set_rein_asean','claim_set_rein_other',
                           'claim_set_total_rein','claim_rcv_rein_sg','claim_rcv_rein_asean','claim_rcv_rein_other',
                           'claim_rcv_rein_total','claim_set_net','claim_liab_end','claim_liab_begin',
                           'claim_incur_net','exp_management','exp_comm_paid','exp_comm_earned','exp_comm_incur_net']
        df2_column_drop = [0,1]
        df2_labels_drop = [0,2,6]
        df2_index_names = ['exp_other','uw_gain','net_invest_income','operating_result']        

    elif split_type == 5:
        df1_column_drop = ['Unnamed: 0','Unnamed: 1','Unnamed: 2']
        df1_labels_drop = [0,1,2,3,4,5,6,7,9,14,20,22,24,26,27,28,30,35,36,43,45,47,49]
        df1_index_names = ['prem_acc_direct','prem_acc_rein_sg','prem_acc_rein_asean','prem_acc_rein_other',
                           'prem_acc_total_rein','prem_cede_rein_sg','prem_cede_rein_asean','prem_cede_rein_other',
                           'prem_cede_rein_total','prem_write_net','prem_liab_begin','prem_liab_end','prem_earned',
                           'claim_set_direct','claim_set_rein_sg','claim_set_rein_asean','claim_set_rein_other',
                           'claim_set_total_rein','claim_rcv_rein_sg','claim_rcv_rein_asean','claim_rcv_rein_other',
                           'claim_rcv_rein_total','claim_set_net','claim_liab_end','claim_liab_begin',
                           'claim_incur_net','exp_management','exp_comm_paid','exp_comm_earned']
        df2_column_drop = [0,1]
        df2_labels_drop = [2,6]
        df2_index_names = ['exp_comm_incur_net','exp_other','uw_gain','net_invest_income','operating_result']  
        
    else:
        print("ERROR: Unrecognized split_type!")

    # format df1
    df1.drop(columns=df1_column_drop, inplace=True)
    df1.drop(labels=df1_labels_drop ,inplace=True)
    df1.dropna(axis=1,inplace=True) # drop columns that contain NaN/null
    df1_columns = list(df1.columns.values)
    renamedict1 = {df1_columns[0]:'mac', df1_columns[1]:'mahl', df1_columns[2]:'fire',
                       df1_columns[3]:'motor', df1_columns[4]:'wic', df1_columns[5]:'pa',
                       df1_columns[6]:'health', df1_columns[7]:'pub_lia', df1_columns[8]:'bonds',
                       df1_columns[9]:'cnstr_engr', df1_columns[10]:'prof_indm', df1_columns[11]:'cpr',
                       df1_columns[12]:'others', df1_columns[13]:'misc_total', df1_columns[14]:'total'}

    df1.rename(columns=renamedict1, inplace=True)
    df1['index_name'] = df1_index_names
    df1.set_index('index_name', inplace=True)
        
    # format df2
    df2.fillna(value=0, axis=0, inplace=True) # fill NaN with 0s - targeting the'Other Distribution Expenses' row
    df2.drop(columns=df2_column_drop, inplace=True)
    df2.drop(labels=df2_labels_drop, inplace=True)
    df2.dropna(axis=1, inplace=True)
    df2_columns = list(df2.columns.values)
    renamedict2 = {df2_columns[0]:'mac', df2_columns[1]:'mahl', df2_columns[2]:'fire',
                       df2_columns[3]:'motor', df2_columns[4]:'wic', df2_columns[5]:'pa',
                       df2_columns[6]:'health', df2_columns[7]:'pub_lia', df2_columns[8]:'bonds',
                       df2_columns[9]:'cnstr_engr', df2_columns[10]:'prof_indm', df2_columns[11]:'cpr',
                       df2_columns[12]:'others', df2_columns[13]:'misc_total', df2_columns[14]:'total'}

    df2.rename(columns=renamedict2, inplace=True)
    df2['index_name'] = df2_index_names
    df2.set_index('index_name', inplace=True)
    
    # concatenate df1 & df2 into one table
    df = pd.concat([df1,df2])
    return df

# Define Function pdf_to_df()

In [27]:
# this is the main function that converts the PDF table into a dataframe
# if the PDF is split across 2 pages, then 2 PDF files would have been generated, otherwise, only 1 PDF file.

def pdf_to_df(filepath1, filepath2, company_prefix, record_year):

    print(company_prefix,'year',record_year,'\tfilepath1:',filepath1,'  filepath2:',filepath2)
    global exception_file_list # declare this global variable
    
    df1 = tabula.read_pdf(filepath1) # read file1
        
    if filepath2 != "": # not empty => the table was split across 2 pages
        
        # read file2 - set pandas_options to insert a header row
        df2 = tabula.read_pdf(filepath2, pandas_options={'header': -1}) 
        
        # check how the table was split up, then call the handler accordingly
        
        if (df1.shape[0] == 49) and (df2.shape[0] == 6): # Table split into 30/4         
            df = split_table_handler(df1, df2, 1)
        
        elif (df1.shape[0] == 46) and (df2.shape[0] == 6): # Table split into 31/3
            df = split_table_handler(df1, df2, 2)
            
        elif (df1.shape[0] == 50) and (df2.shape[0] == 3): # Table split into 32/2
            df = split_table_handler(df1, df2, 3)
        
        elif (df1.shape[0] == 53) and (df2.shape[0] == 7): # Table split into 30/4
            df = split_table_handler(df1, df2, 4)
            
        elif (df1.shape[0] == 52) and (df2.shape[0] == 7): # Table split into 29/5
            df = split_table_handler(df1, df2, 5)            
      
        else:
            # Unseen split type - put filename1&2 (as tuple) in global exception list
            exception_file_list.append((filepath1,filepath2))
            print('Error: Unrecognized split type ...')
    
    else: # the table is CONTAINED IN 1 PAGE - there is only one format to deal with
        
        df = df1.copy() # we want our dataframe to be named "df"
        df.drop(columns=['Unnamed: 0','Unnamed: 1','Unnamed: 2'],inplace=True)
        df.drop(labels=[0,1,2,3,4,5,7,12,21,22,24,29,38,40,45],inplace=True)
        df.dropna(axis=1,inplace=True)
        df_columns = list(df.columns.values)
        rename_dict = {df_columns[0]:'mac', df_columns[1]:'mahl', df_columns[2]:'fire',
                       df_columns[3]:'motor', df_columns[4]:'wic', df_columns[5]:'pa',
                       df_columns[6]:'health', df_columns[7]:'pub_lia', df_columns[8]:'bonds',
                       df_columns[9]:'cnstr_engr', df_columns[10]:'prof_indm', df_columns[11]:'cpr',
                       df_columns[12]:'others', df_columns[13]:'misc_total', df_columns[14]:'total'}
        
        df.rename(columns=rename_dict,inplace=True)           
        df['index_name']=['prem_acc_direct','prem_acc_rein_sg','prem_acc_rein_asean','prem_acc_rein_other',
                          'prem_acc_total_rein','prem_cede_rein_sg','prem_cede_rein_asean','prem_cede_rein_other',
                          'prem_cede_rein_total','prem_write_net','prem_liab_begin','prem_liab_end','prem_earned',
                          'claim_set_direct','claim_set_rein_sg','claim_set_rein_asean','claim_set_rein_other',
                          'claim_set_total_rein','claim_rcv_rein_sg','claim_rcv_rein_asean','claim_rcv_rein_other',
                          'claim_rcv_rein_total','claim_set_net','claim_liab_end','claim_liab_begin',
                          'claim_incur_net','exp_management','exp_comm_paid','exp_comm_earned','exp_comm_incur_net',
                          'exp_other','uw_gain','net_invest_income','operating_result']
        df.set_index('index_name', inplace=True)
    
    ####### DATAFRAME HAS BEEN PREPARED / MERGED #######
    
    # transpose the table, clean/transform data to correct type, insert columns and reset index   
    # For tables on 1 page, brackets are used for negative numbers
    # For tables on 2 pages, minus sign is used
    # Remove brackets and commas. Where brackets are used for negative numbers, replace with minus sign.
    df = df.T
    df = df.applymap(lambda x: str(x).replace(',','')) # remove commas
    df = df.applymap(lambda x: str(x).replace(')','')) # remove closing bracket
    df = df.applymap(lambda x: float(str(x).replace('(','-'))) # replace opening bracket with minus, change to float
    df.reset_index(inplace=True) # reset the index
    df.rename(columns={'index':'class'},inplace=True)
    del df.index.name
    df.insert(0,column='company',value=company_prefix)
    df.insert(0,column='year',value=record_year)
    return df # return the dataframe

# Define Function check_output_data_shape()

In [28]:
# function to check the shape of the dataframe that was obtained from the latest PDF file(s)

def check_output_data_shape(filename,shape_tuple):
    global exception_file_list # use the global variable
    if (shape_tuple[0]==15) and (shape_tuple[1]==37):
        pass
    else:
        exception_file_list.append(filename)
        print('ALERT: Output shape does not comply with (15,37)!',shape_tuple)
    return

# Main Loop

In [29]:
source_folder = '../data/output/'
list_of_files = os.listdir(path=source_folder)
len_list_of_files = len(list_of_files)
i_prev = 'abcdefhhijk'
# Global variable
exception_file_list = [] # filenames with exceptions to be appended here

# # LIMIT LOOPS for test purpose
# testloops = 20
# testcount=0

# create master dataframe (empty) with 37 columns
df_master = pd.DataFrame([],columns=['year','company','class','prem_acc_direct','prem_acc_rein_sg',
                                  'prem_acc_rein_asean','prem_acc_rein_other','prem_acc_total_rein',
                                  'prem_cede_rein_sg','prem_cede_rein_asean','prem_cede_rein_other',
                                  'prem_cede_rein_total','prem_write_net','prem_liab_begin','prem_liab_end',
                                  'prem_earned','claim_set_direct','claim_set_rein_sg','claim_set_rein_asean',
                                  'claim_set_rein_other','claim_set_total_rein','claim_rcv_rein_sg',
                                  'claim_rcv_rein_asean','claim_rcv_rein_other','claim_rcv_rein_total',
                                  'claim_set_net','claim_liab_end','claim_liab_begin','claim_incur_net',
                                  'exp_management','exp_comm_paid','exp_comm_earned','exp_comm_incur_net',
                                  'exp_other','uw_gain','net_invest_income','operating_result'])

for count, i in enumerate(list_of_files):
    filepath1 = source_folder + i
    
    if i_prev == 'abcdefhhijk': # this is the first iteration - skip and go to next iteration
        i_prev = i
        pass

    else:
        if i[:9] == i_prev[:9]: # current/previous file have same name => table is split across 2 pages
            filepath1 = source_folder + i_prev # prepare to merge; set file 1 to previous file
            filepath2 = source_folder + i # prepare to merge; set file 2 to current file
            company_prefix = i[0:4]
            record_year = i[5:9]    
            df = pdf_to_df(filepath1, filepath2, company_prefix, record_year)
            df_master = pd.concat([df_master,df])
            
            #debug
            debug_filename = i
#             df.to_csv('../data/debug/' + debug_filename[:-3] + 'csv')
            check_output_data_shape(debug_filename, df.shape)
            
            # final update for this section
            i_prev = 'abcdefhhijk' # make the next iteration look like the first iteration again
                
        else: # current/previous file have different name => table in previous file is on 1 page only
            filepath1 = source_folder + i_prev # prepare to process previous file
            filepath2 = "" # make this empty
            company_prefix = i_prev[0:4]
            record_year = i_prev[5:9]                
            df = pdf_to_df(filepath1, filepath2, company_prefix, record_year)
            df_master = pd.concat([df_master,df])
            
            #debug
            debug_filename = i_prev
#             df.to_csv('../data/debug/' + debug_filename[:-3] + 'csv')
            check_output_data_shape(debug_filename, df.shape)
            
            # final update for this section
            i_prev = i # the current file shall be treated as the 'previous file' in next iteration    

            # if this is already the last iteration, then extract this file anyway.
            if count == (len_list_of_files-1):
                # force output
                filepath1 = source_folder + i_prev
                filepath2 = ""
                df = pdf_to_df(filepath1, filepath2, company_prefix, record_year)
                df_master = pd.concat([df_master,df])
                
                #debug
#                 df.to_csv('../data/debug/' + i[:-3] + 'csv')
                check_output_data_shape(i, df.shape)
    
    # LIMIT LOOPS for test purpose
#     testcount+=1
#     if testcount == testloops:
#         break

# Export to CSV files
df_master.to_csv('../data/debug/master.csv')
pd.Series(exception_file_list).to_csv('../data/debug/exceptions.csv')

c152 year 2015 	filepath1: ../data/output/c152_2015_page_14.pdf   filepath2: ../data/output/c152_2015_page_15.pdf
c152 year 2016 	filepath1: ../data/output/c152_2016_page_14.pdf   filepath2: ../data/output/c152_2016_page_15.pdf
c152 year 2017 	filepath1: ../data/output/c152_2017_page_13.pdf   filepath2: ../data/output/c152_2017_page_14.pdf
c152 year 2018 	filepath1: ../data/output/c152_2018_page_14.pdf   filepath2: ../data/output/c152_2018_page_15.pdf

C:\Users\XXX\Anaconda3\lib\site-packages\ipykernel_launcher.py:83: FutureWarning: The signature of `Series.to_csv` was aligned to that of `DataFrame.to_csv`, and argument 'header' will change its default value from False to True: please pass an explicit value to suppress this warning.

# Review Dataframe

In [30]:
df_master = pd.read_csv('../data/debug/master.csv')

In [31]:
df_master.shape

(16140, 38)

In [32]:
df_master.head()

,Unnamed: 0,year,company,class,prem_acc_direct,prem_acc_rein_sg,prem_acc_rein_asean,prem_acc_rein_other,prem_acc_total_rein,prem_cede_rein_sg,prem_cede_rein_asean,prem_cede_rein_other,prem_cede_rein_total,prem_write_net,prem_liab_begin,prem_liab_end,prem_earned,claim_set_direct,claim_set_rein_sg,claim_set_rein_asean,claim_set_rein_other,claim_set_total_rein,claim_rcv_rein_sg,claim_rcv_rein_asean,claim_rcv_rein_other,claim_rcv_rein_total,claim_set_net,claim_liab_end,claim_liab_begin,claim_incur_net,exp_management,exp_comm_paid,exp_comm_earned,exp_comm_incur_net,exp_other,uw_gain,net_invest_income,operating_result
0,0,2007,c001,mac,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,2007,c001,mahl,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2,2007,c001,fire,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,3,2007,c001,motor,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,2007,c001,wic,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

In [33]:
df_master.drop(columns=['Unnamed: 0'],inplace=True)

In [35]:
df_master.reset_index(inplace=True)

In [36]:
df_master

,index,year,company,class,prem_acc_direct,prem_acc_rein_sg,prem_acc_rein_asean,prem_acc_rein_other,prem_acc_total_rein,prem_cede_rein_sg,prem_cede_rein_asean,prem_cede_rein_other,prem_cede_rein_total,prem_write_net,prem_liab_begin,prem_liab_end,prem_earned,claim_set_direct,claim_set_rein_sg,claim_set_rein_asean,claim_set_rein_other,claim_set_total_rein,claim_rcv_rein_sg,claim_rcv_rein_asean,claim_rcv_rein_other,claim_rcv_rein_total,claim_set_net,claim_liab_end,claim_liab_begin,claim_incur_net,exp_management,exp_comm_paid,exp_comm_earned,exp_comm_incur_net,exp_other,uw_gain,net_invest_income,operating_result
0,0,2007,c001,mac,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,1,2007,c001,mahl,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,2,2007,c001,fire,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,3,2007,c001,motor,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4,4,2007,c001,wic,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,5,2007,c001,pa,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,6,2007,c001,health,1905531,9586479,0,0,9586479,0,0,0,0,11492010,0,181000,11311010,1272871,6336590,0,0,6336590,0,0,0,0,7609461,2967000,0,10576461,2247901,779,0,779,0,-1514131,2061033,546902
7,7,2007,c001,pub_lia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
8,8,2007,c001,bonds,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,9,2007,c001,cnstr_engr,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
10,10,2007,c001,prof_indm,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,11,2007,c001,cpr,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,12,2007,c001,others,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,13,2007,c001,misc_total,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,14,2007,c001,total,1905531,9586479,0,0,9586479,0,0,0,0,11492010,0,181000,11311010,1272871,6336590,0,0,6336590,0,0,0,0,7609461,2967000,0,10576461,2247901,779,0,779,0,-1514131,2061033,546902
15,15,2009,c002,mac,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,16,2009,c002,mahl,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
17,17,2009,c002,fire,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,18,2009,c002,motor,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,19,2009,c002,wic,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
20,20,2009,c002,pa,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,21,2009,c002,health,5105503,0,0,0,0,0,0,18176,18176,5087327,-122589,3656745,1307993,694266,0,0,0,0,0,0,0,0,694266,1049173,-35173,1778612,402004,601793,0,601793,0,-1474416,2170,-1472246
22,22,2009,c002,pub_lia,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
23,23,2009,c002,bonds,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,24,2009,c002,cnstr_engr,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
16115,16115,2017,c172,pa,4067065,441868,0,0,441868,0,0,3368411,3368411,1140522,863142,522811,1480853,2612585,271646,0,0,271646,0,0,574280,574280,2309951,1617625,2005757,1921819,995484,1043838,932714,111124,0,-1547574,182485,-1365089
16116,16116,2017,c172,health,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16117,16117,2017,c172,pub_lia,4583229,776511,0,0,776511,0,0,4782326,4782326,577414,557288,933732,200970,6461980,0,0,0,0,0,0,5937714,5937714,524266,1275665,2835791,-1035860,1183325,625977,1558260,-932283,0,985788,216919,1202707
16118,16118,2017,c172,bonds,149289,0,0,0,0,0,0,327523,327523,-178234,339290,26542,134514,0,0,0,0,0,0,0,0,0,0,15125,6994,8131,32960,406347,82461,323886,0,-230463,6042,-224421
16119,16119,2017,c172,cnstr_engr,5281164,2472054,0,0,2472054,0,0,6498111,6498111,1255107,799582,2255800,-201111,1740987,887310,0,0,887310,0,0,2603075,2603075,25222,88485,142758,-29051,1711758,521138,1066101,-544963,0,-1338855,313787,-1025068
16120,16120,2017,c172,prof_indm,3428533,47366,0,0,47366,0,0,2540720,2540720,935179,387190,595905,726464,801418,0,0,0,0,0,0,760753,760753,40665,569942,215791,394816,767410,461362,843275,-381913,0,-53849,140676,86827
16121,16121,2017,c172,cpr,7840185,0,0,0,0,0,0,7840185,7840185,0,825423,709959,115464,-4943824,0,0,0,0,0,0,-4943824,-4943824,0,0,0,0,1730958,1097565,2134287,-1036722,0,-578772,317307,-261465
16122,16122,2017,c172,others,272865,119528,0,0,119528,0,0,330266,330266,62127,15849,25747,52229,2032,0,0,0,0,0,0,483,483,1549,9913,3023,8439,86632,39848,86454,-46606,0,3764,15880,19644
16123,16123,2017,c172,misc_total,21555265,3415459,0,0,3415459,0,0,22319131,22319131,2651593,2924622,4547685,1028530,4062593,887310,0,0,887310,0,0,4358201,4358201,591702,1959130,3204357,-653525,5513043,3152237,5770838,-2618601,0,-1212387,1010611,-201776
16124,16124,2017,c172,total,42749401,6097095,0,0,6097095,0,0,44556682,44556682,4289814,5810239,6321564,3778489,11856362,2235791,0,0,2235791,0,0,10368695,10368695,3723458,6263859,10027854,-40537,10784344,5611612,9709595,-4097983,0,-2867335,1976909,-890426
16125,16125,2018,c172,mac,2016650,67941,0,0,67941,0,0,2073930,2073930,10661,240028,193654,57035,530382,8146,0,0,8146,0,0,532872,532872,5656,874371,901998,-21971,498174,436621,646535,-209914,0,-209254,5742,-203512
16126,16126,2018,c172,mahl,1580,0,0,0,0,0,0,1580,1580,0,0,0,0,1397,0,0,0,0,0,0,419,419,978,159791,164799,-4030,378,0,1580,-1580,0,5232,4,5236
16127,16127,2018,c172,fire,14448934,1151761,0,0,1151761,0,0,14803826,14803826,796869,940838,1082229,655478,2197826,104417,0,0,104417,0,0,1809326,1809326,492917,1676982,1619234,550665,3728240,1061690,2642872,-1581182,0,-2042245,42969,-1999276
16128,16128,2018,c172,motor,80687,0,0,0,0,0,0,80903,80903,-216,3483,4139,-872,21475,0,0,0,0,0,0,21475,21475,0,0,1073,-1073,19283,6543,25182,-18639,0,-443,222,-221
16129,16129,2018,c172,wic,1498897,0,0,0,0,0,0,1501245,1501245,-2348,66719,81101,-16730,958225,0,0,0,0,0,0,958225,958225,0,0,0,0,358205,91209,286570,-195361,0,-179574,4128,-175446
16130,16130,2018,c172,pa,3925761,42662,0,0,42662,0,0,2358719,2358719,1609704,522811,482805,1649710,2383690,106150,0,0,106150,0,0,1154330,1154330,1335510,1306485,1617625,1024370,948370,815294,713237,102057,0,-425087,10930,-414157
16131,16131,2018,c172,health,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16132,16132,2018,c172,pub_lia,4035596,361747,0,0,361747,0,0,4210151,4210151,187192,933732,931882,189042,542308,0,0,0,0,0,0,538283,538283,4025,1148783,1275665,-122857,1050873,522712,1331460,-808748,0,69774,12112,81886
16133,16133,2018,c172,bonds,1001028,0,0,0,0,0,0,932261,932261,68767,26542,154505,-59196,0,0,0,0,0,0,0,0,0,0,14798,15125,-327,239225,-228700,84882,-313582,0,15488,2757,18245
16134,16134,2018,c172,cnstr_engr,4931480,287458,0,0,287458,0,0,5063093,5063093,155845,2255800,2252721,158924,75942,198411,0,0,198411,0,0,264061,264061,10292,372022,88485,293829,1247217,167089,473557,-306468,0,-1075654,14375,-1061279
16135,16135,2018,c172,prof_indm,4201119,47975,0,0,47975,0,0,3129223,3129223,1119871,595905,796620,919156,873344,0,0,0,0,0,0,677564,677564,195780,1249337,569942,875175,1015445,578402,948746,-370344,0,-601120,11703,-589417
16136,16136,2018,c172,cpr,5119318,0,0,0,0,0,0,5119318,5119318,0,709959,408665,301294,34678522,0,0,0,0,0,0,34678522,34678522,0,0,0,0,1223410,726612,1296446,-569834,0,-352282,14100,-338182
16137,16137,2018,c172,others,287608,119588,0,0,119588,0,0,296421,296421,110775,25747,26485,110037,0,0,0,0,0,0,0,0,0,0,7830,9913,-2083,97311,45083,71544,-26461,0,41270,1122,42392
16138,16138,2018,c172,misc_total,19576149,816768,0,0,816768,0,0,18750467,18750467,1642450,4547685,4570878,1619257,36170116,198411,0,0,198411,0,0,36158430,36158430,210097,2792770,1959130,1043737,4873481,1811198,4206635,-2395437,0,-1902524,56169,-1846355
16139,16139,2018,c172,total,41548658,2079132,0,0,2079132,0,0,39570670,39570670,4057120,6321564,6414806,3963878,42263111,417124,0,0,417124,0,0,40635077,40635077,2045158,6810399,6263859,2591698,10426131,4222555,8522611,-4300056,0,-4753895,120164,-4633731

# Export Dataframe to CSV

In [38]:
df_master.to_csv('../data/master.csv',index=False)


# Additional Debugging / Exploratory Code

## Debug usage of Tabula

In [1]:
# DEBUG TABULA usage (1-page table)

source_folder = '../data/output/'
file1 = 'c001_2007_page_52.pdf'
file2 = 'c006_2013_page_54.pdf'

df1 = tabula.read_pdf(source_folder+file1)
df1.drop(columns=['Unnamed: 0','Unnamed: 1','Unnamed: 2'],inplace=True)
df1.drop(labels=[0,1,2,3,4,5,7,12,21,22,24,29,38,40,45],inplace=True)
df1.dropna(axis=1,inplace=True)

df2 = tabula.read_pdf(source_folder+file2)
df2.drop(columns=['Unnamed: 0','Unnamed: 1','Unnamed: 2'],inplace=True)
df2.drop(labels=[0,1,2,3,4,5,7,12,21,22,24,29,38,40,45],inplace=True)
df2.dropna(axis=1,inplace=True)

df1_columns = list(df1.columns.values)
df2_columns = list(df2.columns.values)

print(len(df1_columns),len(df2_columns))

renamedict1 = {df1_columns[0]:'mac', df1_columns[1]:'mahl', df1_columns[2]:'fire',
               df1_columns[3]:'motor', df1_columns[4]:'wic', df1_columns[5]:'pa',
               df1_columns[6]:'health', df1_columns[7]:'pub_lia', df1_columns[8]:'bonds',
               df1_columns[9]:'cnstr_engr', df1_columns[10]:'prof_indm', df1_columns[11]:'cpr',
               df1_columns[12]:'others', df1_columns[13]:'misc_total', df1_columns[14]:'total'}

renamedict2 = {df2_columns[0]:'mac', df2_columns[1]:'mahl', df2_columns[2]:'fire',
               df2_columns[3]:'motor', df2_columns[4]:'wic', df2_columns[5]:'pa',
               df2_columns[6]:'health', df2_columns[7]:'pub_lia', df2_columns[8]:'bonds',
               df2_columns[9]:'cnstr_engr', df2_columns[10]:'prof_indm', df2_columns[11]:'cpr',
               df2_columns[12]:'others', df2_columns[13]:'misc_total', df2_columns[14]:'total'}

df1.rename(columns=renamedict1, inplace=True)
df2.rename(columns=renamedict2, inplace=True)

# output 
df1.to_csv('../data/debug/' + file1[:-3] + 'csv')
df2.to_csv('../data/debug/' + file2[:-3] + 'csv')

NameError: name 'tabula' is not defined


## Explore table split types

In [21]:
source_folder = '../data/output/'
#split-type 1
# file1 = 'c007_2018_page_53.pdf' # table part 1
# file2 = 'c007_2018_page_54.pdf' # table part 2

#split-type 2
# file1 = 'c015_2018_page_51.pdf' # table part 1
# file2 = 'c015_2018_page_52.pdf' # table part 2

#split-type 3
# file1 = 'c008_2015_page_51.pdf' # table part 1
# file2 = 'c008_2015_page_52.pdf' # table part 2

#split-type 4
file1 = 'c152_2018_page_14.pdf' # table part 1
file2 = 'c152_2018_page_15.pdf' # table part 2

### df1
df1 = tabula.read_pdf(source_folder+file1)
### df2
df2 = tabula.read_pdf(source_folder+file2, pandas_options={'header': -1}) # returns with a header row

In [22]:
# split_type 4
print(df1.shape,df2.shape)

(52, 30) (7, 17)

In [24]:
df1.to_csv('../data/debug/' + file1[:-3] + 'csv')
df2.to_csv('../data/debug/' + file2[:-3] + 'csv')

In [ ]:
### USE THIS TO EXPLORE SPLIT TABLES ###
source_folder = '../data/output/'
file1 = 'c017_2016_page_14.pdf' # table part 1
file2 = 'c017_2016_page_15.pdf' # table part 2

### df1
df1 = tabula.read_pdf(source_folder+file1)
print(df1.shape)
# output
df1.to_csv('../data/debug/' + file1[:-3] + 'csv')


### df2
df2 = tabula.read_pdf(source_folder+file2, pandas_options={'header': -1}) # returns with a header row
print(df2.shape)
#output
df2.to_csv('../data/debug/' + file2[:-3] + 'csv')

In [ ]:
df1.tail()

In [ ]:
source_folder = '../data/output/'
file1 = 'c015_2018_page_51.pdf' # table part 1
file2 = 'c015_2018_page_52.pdf' # table part 2

### df1
df1 = tabula.read_pdf(source_folder+file1)
df1.drop(columns=['Unnamed: 0','Unnamed: 1','Unnamed: 2'],inplace=True)
df1.drop(labels=[0,1,2,3,4,5,6,7,9,14,22,24,25,26,28,33,34,43,45],inplace=True)
df1.dropna(axis=1,inplace=True) # drop columns that contain NaN/null
df1_columns = list(df1.columns.values)

renamedict1 = {df1_columns[0]:'mac', df1_columns[1]:'mahl', df1_columns[2]:'fire',
               df1_columns[3]:'motor', df1_columns[4]:'wic', df1_columns[5]:'pa',
               df1_columns[6]:'health', df1_columns[7]:'pub_lia', df1_columns[8]:'bonds',
               df1_columns[9]:'cnstr_engr', df1_columns[10]:'prof_indm', df1_columns[11]:'cpr',
               df1_columns[12]:'others', df1_columns[13]:'misc_total', df1_columns[14]:'total'}

df1.rename(columns=renamedict1, inplace=True)

df1['index_name']=['prem_acc_direct','prem_acc_rein_sg','prem_acc_rein_asean','prem_acc_rein_other',
                          'prem_acc_total_rein','prem_cede_rein_sg','prem_cede_rein_asean','prem_cede_rein_other',
                          'prem_cede_rein_total','prem_write_net','prem_liab_begin','prem_liab_end','prem_earned',
                          'claim_set_direct','claim_set_rein_sg','claim_set_rein_asean','claim_set_rein_other',
                          'claim_set_total_rein','claim_rcv_rein_sg','claim_rcv_rein_asean','claim_rcv_rein_other',
                          'claim_rcv_rein_total','claim_set_net','claim_liab_end','claim_liab_begin',
                          'claim_incur_net','exp_management','exp_comm_paid','exp_comm_earned','exp_comm_incur_net']

df1.set_index('index_name', inplace=True)

# output
df1.to_csv('../data/debug/' + file1[:-3] + 'csv')


### df2
df2 = tabula.read_pdf(source_folder+file2, pandas_options={'header': -1}) # returns with a header row
df2.drop(columns=[0,1],inplace=True)
df2.drop(labels=[1,5],inplace=True)
df2.dropna(axis=1,inplace=True)
df2_columns = list(df2.columns.values)

renamedict2 = {df2_columns[0]:'mac', df2_columns[1]:'mahl', df2_columns[2]:'fire',
               df2_columns[3]:'motor', df2_columns[4]:'wic', df2_columns[5]:'pa',
               df2_columns[6]:'health', df2_columns[7]:'pub_lia', df2_columns[8]:'bonds',
               df2_columns[9]:'cnstr_engr', df2_columns[10]:'prof_indm', df2_columns[11]:'cpr',
               df2_columns[12]:'others', df2_columns[13]:'misc_total', df2_columns[14]:'total'}

df2.rename(columns=renamedict2, inplace=True)
df2['index_name'] = ['exp_other','uw_gain','net_invest_income','operating_result']
df2.set_index('index_name', inplace=True)

#output
df2.to_csv('../data/debug/' + file2[:-3] + 'csv')

## Processing of Negative Numbers in Tables

In [ ]:
df = pd.concat([df1,df2]) # concatenate into one table

# transpose the table, clean/transform data to correct type, insert columns and reset index
df = df.T
    
# For tables on 1 page, brackets are used for negative numbers
# For tables on 2 pages, minus sign is used
# Remove brackets and commas. Where brackets are used for negative numbers, replace with minus sign.
df = df.applymap(lambda x: str(x).replace(',','')) # remove commas
df = df.applymap(lambda x: str(x).replace(')','')) # remove closing bracket
df = df.applymap(lambda x: float(str(x).replace('(','-'))) # replace opening bracket with minus and change to float
df.reset_index(inplace=True) # reset the index
df.rename(columns={'index':'class'},inplace=True)
del df.index.name
df.insert(0,column='company',value=company_prefix)
df.insert(0,column='year',value=record_year)

#output
df.to_csv('../data/debug/MERGED.csv')